name: transit-mogul
version: "0.1.0-dev"
summary: "Transit Mogul is an open source transit/business game forked from OpenTTD."
description: |
  Transit Mogul is an open source transit/business simulation game forked from 
  OpenTTD. You get to play with trains, buses, trucks, and ships in order to 
  build a transit empire.
grade: stable
confinement: strict
base: core
apps:
  transit-mogul:
    command: desktop-launch $SNAP/opt/transit-mogul/transit-mogul
    plugs:
      - alsa
      - network
      - network-bind
      - opengl
      - pulseaudio
      - x11
parts:
  abase:
    plugin: dump
    source: http://binaries.openttd.org/bananas/basegraphic/abase-0.1.2.tar.gz
    override-build: |
      snapcraft build
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/abase
      cp -r * $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/abase/
    after: [transit-mogul]
  transit-mogul:
    plugin: autotools
    source: .
    build-packages:
      - build-essential
      - libfontconfig1-dev
      - libicu-dev
      - liblzma-dev
      - liblzo2-dev
      - libsdl1.2-dev
      - patch
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - fontconfig
      - freepats
      - libfreetype6
      - libglu1-mesa
      - libgl1-mesa-dri
      - libicu55
      - liblzma5
      - liblzo2-2
      - libpng12-0
      - libpulse0
      - libsdl1.2debian
      - libxdamage1
      - libx11-xcb1
      - timidity
      - zlib1g
    override-build: |
      ./configure
      make -j$(nproc)
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/
      cp -r bin/* $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/
    after: [desktop-glib-only]
#  opengfx:
#    plugin: make
#    source: https://binaries.openttd.org/extra/opengfx/0.5.2/opengfx-0.5.2-source.tar.xz
#    build-packages:
#      - dos2unix
#      - gcc
#      # Yes, we do indeed need GIMP
#      - gimp
#      - grfcodec
#      - nml
#      - tar
#    build: make
#    install: |
#      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/opengfx/
#      cp -r opengfx-0.5.2/* $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/opengfx/
#    after: [transit-mogul]
  openmsx:
    plugin: make
    source: https://binaries.openttd.org/extra/openmsx/0.3.1/openmsx-0.3.1-source.tar.gz
    build-packages:
      - dos2unix
      - python
    override-build: |
      make
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/openmsx/
      cp openmsx.obm $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/openmsx/
      cp src/* $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/openmsx/
      cp docs/* $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/openmsx/
    after: [transit-mogul]
  opensfx:
    plugin: make
    source: https://binaries.openttd.org/extra/opensfx/0.2.3/opensfx-0.2.3-source.tar.gz
    build-packages:
      - catcodec
    override-build: |
      make
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/opensfx/
      cp opensfx.cat $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/opensfx/
      cp opensfx.obs $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/opensfx/
      cp docs/* $SNAPCRAFT_PART_INSTALL/opt/transit-mogul/baseset/opensfx/
    after: [transit-mogul]
